name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Usar Python 3.11 para evitar problemas com distutils, ou 3.12 se o buildozer-action for atualizado

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake

    - name: Install Buildozer
      run: pip install buildozer

    - name: Initialize Buildozer (if buildozer.spec doesn't exist)
      run: buildozer init || true
      working-directory: ./CalcularCerveja # Ajuste para o diretório do seu projeto Kivy

    - name: Build Android APK
      run: buildozer android debug
      working-directory: ./CalcularCerveja # Ajuste para o diretório do seu projeto Kivy

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: ./CalcularCerveja/bin/*.apk # Ajuste para o diretório do seu projeto Kivy
