name: Build Signed APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Suporta acionamento manual

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode Keystore from Secrets
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > cerveja-keystore.jks

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android release

      - name: Sign APK
        run: |
          APK_PATH=$(find ./bin -name "*release-unsigned.apk" | head -n 1)
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore cerveja-keystore.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            "$APK_PATH" "${{ secrets.KEY_ALIAS }}"
          mv "$APK_PATH" "${APK_PATH/-unsigned/-signed}"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: ./bin/*-signed.apk
